[package]
name = "cpp_common"
version = "0.4.0"
authors = ["Nika Layzell <nika@thelayzells.com>", "Olivier Goffart <ogoffart@woboq.com>"]
description = "Implementation details crate for the `cpp` crate"
readme = "../README.md"
license = "MIT/Apache-2.0"
keywords = ["c", "cxx", "ffi", "compiler", "build-dependencies"]
categories = ["development-tools::ffi"]
repository = "https://github.com/mystor/rust-cpp"
documentation = "https://docs.rs/cpp_common"

[dependencies]
syn = { version = "0.14", features = ["full", "visit", "extra-traits"] }
lazy_static = "1.0"
quote = "0.6"
proc-macro2 = "0.4"
